SELECT * FROM [dbo].[VCChangeSet]
SELECT * FROM [dbo].[VCCheckOut]
SELECT * FROM [dbo].[VCLabel]
SELECT * FROM [dbo].[VCLabelVersion]
SELECT * FROM [dbo].[VCMergePoint]
SELECT * FROM [dbo].[VCProcessVersion]
SELECT * FROM [dbo].[VCRepository]
SELECT * FROM [dbo].[VCSysInfo]